### ISSUE TITLE
How does this work using T5 compare with DeepCommenter (https://github.com/SpringHerald/DeepCommenter)

### ISSUE THREAD

**Issue by Manas-Embold** [codekali/Neural-SC-Descriptor#1]

**Comment by Manas-Embold** [comment]
How is the performance in comparison with DeepCommenter.
Are there any performance improvements.

**Comment by codekali** [comment]
Sorry for the late reply. We couldn't improve on performance compared to DeepCommenter due to lack of resources during Lockdown. Currently work is stopped on the project, we will soon resume its research.

**Comment by Manas-Embold** [comment]
Thanks much for response.
